// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/limiter/v1/limiter.proto

package limiterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Algorithm int32

const (
	Algorithm_ALGORITHM_UNSPECIFIED    Algorithm = 0
	Algorithm_ALGORITHM_TOKEN_BUCKET   Algorithm = 1
	Algorithm_ALGORITHM_SLIDING_WINDOW Algorithm = 2
	Algorithm_ALGORITHM_LEAKY_BUCKET   Algorithm = 3
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "ALGORITHM_UNSPECIFIED",
		1: "ALGORITHM_TOKEN_BUCKET",
		2: "ALGORITHM_SLIDING_WINDOW",
		3: "ALGORITHM_LEAKY_BUCKET",
	}
	Algorithm_value = map[string]int32{
		"ALGORITHM_UNSPECIFIED":    0,
		"ALGORITHM_TOKEN_BUCKET":   1,
		"ALGORITHM_SLIDING_WINDOW": 2,
		"ALGORITHM_LEAKY_BUCKET":   3,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_limiter_v1_limiter_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_proto_limiter_v1_limiter_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_proto_limiter_v1_limiter_proto_rawDescGZIP(), []int{0}
}

type BreakerState int32

const (
	BreakerState_BREAKER_STATE_UNSPECIFIED BreakerState = 0
	BreakerState_BREAKER_STATE_CLOSED      BreakerState = 1
	BreakerState_BREAKER_STATE_OPEN        BreakerState = 2
	BreakerState_BREAKER_STATE_HALF_OPEN   BreakerState = 3
)

// Enum value maps for BreakerState.
var (
	BreakerState_name = map[int32]string{
		0: "BREAKER_STATE_UNSPECIFIED",
		1: "BREAKER_STATE_CLOSED",
		2: "BREAKER_STATE_OPEN",
		3: "BREAKER_STATE_HALF_OPEN",
	}
	BreakerState_value = map[string]int32{
		"BREAKER_STATE_UNSPECIFIED": 0,
		"BREAKER_STATE_CLOSED":      1,
		"BREAKER_STATE_OPEN":        2,
		"BREAKER_STATE_HALF_OPEN":   3,
	}
)

func (x BreakerState) Enum() *BreakerState {
	p := new(BreakerState)
	*p = x
	return p
}

func (x BreakerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BreakerState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_limiter_v1_limiter_proto_enumTypes[1].Descriptor()
}

func (BreakerState) Type() protoreflect.EnumType {
	return &file_proto_limiter_v1_limiter_proto_enumTypes[1]
}

func (x BreakerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BreakerState.Descriptor instead.
func (BreakerState) EnumDescriptor() ([]byte, []int) {
	return file_proto_limiter_v1_limiter_proto_rawDescGZIP(), []int{1}
}

type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identification of client, IP, API key or user (e.g. "client-192.168.1.10", "tenant:acme").
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Selected rate limiting algorithm (defaults to Token Bucket if unspecified).
	Algorithm Algorithm `protobuf:"varint,2,opt,name=algorithm,proto3,enum=limiter.v1.Algorithm" json:"algorithm,omitempty"`
	// Maximum burst / capacity (e.g. 100 tokens or 100 requests).
	Capacity int64 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Refill rate or threshold (e.g. 20 tokens/sec or 20 req/window).
	Rate float64 `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate,omitempty"`
	// Window duration in milliseconds (used for sliding window, e.g. 1000 for 1s).
	WindowMs int64 `protobuf:"varint,5,opt,name=window_ms,json=windowMs,proto3" json:"window_ms,omitempty"`
	// Cost of the operation (defaults to 1 if <= 0).
	Cost int64 `protobuf:"varint,6,opt,name=cost,proto3" json:"cost,omitempty"`
	// Optional target service name to check circuit breaker status alongside rate limiting.
	ServiceName   string `protobuf:"bytes,7,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_v1_limiter_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CheckRequest) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *CheckRequest) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CheckRequest) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *CheckRequest) GetWindowMs() int64 {
	if x != nil {
		return x.WindowMs
	}
	return 0
}

func (x *CheckRequest) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CheckRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the request is permitted.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// Human-readable reason if denied ("RATE_LIMIT_EXCEEDED", "CIRCUIT_BREAKER_OPEN").
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Remaining tokens/capacity in current cycle.
	Remaining float64 `protobuf:"fixed64,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// Approximate duration in milliseconds until next token or window reset.
	RetryAfterMs int64 `protobuf:"varint,4,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	// Current circuit breaker state if service_name was provided.
	BreakerState  BreakerState `protobuf:"varint,5,opt,name=breaker_state,json=breakerState,proto3,enum=limiter.v1.BreakerState" json:"breaker_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_v1_limiter_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckResponse) GetRemaining() float64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *CheckResponse) GetBreakerState() BreakerState {
	if x != nil {
		return x.BreakerState
	}
	return BreakerState_BREAKER_STATE_UNSPECIFIED
}

type RecordResultRequest struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	ServiceName                  string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Success                      bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ConsecutiveFailuresThreshold int64                  `protobuf:"varint,3,opt,name=consecutive_failures_threshold,json=consecutiveFailuresThreshold,proto3" json:"consecutive_failures_threshold,omitempty"` // e.g. 5
	RecoveryTimeoutMs            int64                  `protobuf:"varint,4,opt,name=recovery_timeout_ms,json=recoveryTimeoutMs,proto3" json:"recovery_timeout_ms,omitempty"`                                  // e.g. 10000ms
	ProbeSuccessThreshold        int64                  `protobuf:"varint,5,opt,name=probe_success_threshold,json=probeSuccessThreshold,proto3" json:"probe_success_threshold,omitempty"`                      // e.g. 3
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RecordResultRequest) Reset() {
	*x = RecordResultRequest{}
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResultRequest) ProtoMessage() {}

func (x *RecordResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResultRequest.ProtoReflect.Descriptor instead.
func (*RecordResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_v1_limiter_proto_rawDescGZIP(), []int{2}
}

func (x *RecordResultRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RecordResultRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordResultRequest) GetConsecutiveFailuresThreshold() int64 {
	if x != nil {
		return x.ConsecutiveFailuresThreshold
	}
	return 0
}

func (x *RecordResultRequest) GetRecoveryTimeoutMs() int64 {
	if x != nil {
		return x.RecoveryTimeoutMs
	}
	return 0
}

func (x *RecordResultRequest) GetProbeSuccessThreshold() int64 {
	if x != nil {
		return x.ProbeSuccessThreshold
	}
	return 0
}

type RecordResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	PreviousState BreakerState           `protobuf:"varint,2,opt,name=previous_state,json=previousState,proto3,enum=limiter.v1.BreakerState" json:"previous_state,omitempty"`
	CurrentState  BreakerState           `protobuf:"varint,3,opt,name=current_state,json=currentState,proto3,enum=limiter.v1.BreakerState" json:"current_state,omitempty"`
	FailureCount  int64                  `protobuf:"varint,4,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	SuccessCount  int64                  `protobuf:"varint,5,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordResultResponse) Reset() {
	*x = RecordResultResponse{}
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResultResponse) ProtoMessage() {}

func (x *RecordResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResultResponse.ProtoReflect.Descriptor instead.
func (*RecordResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_v1_limiter_proto_rawDescGZIP(), []int{3}
}

func (x *RecordResultResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RecordResultResponse) GetPreviousState() BreakerState {
	if x != nil {
		return x.PreviousState
	}
	return BreakerState_BREAKER_STATE_UNSPECIFIED
}

func (x *RecordResultResponse) GetCurrentState() BreakerState {
	if x != nil {
		return x.CurrentState
	}
	return BreakerState_BREAKER_STATE_UNSPECIFIED
}

func (x *RecordResultResponse) GetFailureCount() int64 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *RecordResultResponse) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

type BreakerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreakerStatusRequest) Reset() {
	*x = BreakerStatusRequest{}
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreakerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakerStatusRequest) ProtoMessage() {}

func (x *BreakerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakerStatusRequest.ProtoReflect.Descriptor instead.
func (*BreakerStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_v1_limiter_proto_rawDescGZIP(), []int{4}
}

func (x *BreakerStatusRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type BreakerStatusResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ServiceName           string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	State                 BreakerState           `protobuf:"varint,2,opt,name=state,proto3,enum=limiter.v1.BreakerState" json:"state,omitempty"`
	FailureCount          int64                  `protobuf:"varint,3,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	SuccessCount          int64                  `protobuf:"varint,4,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	LastStateChangeUnixMs int64                  `protobuf:"varint,5,opt,name=last_state_change_unix_ms,json=lastStateChangeUnixMs,proto3" json:"last_state_change_unix_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BreakerStatusResponse) Reset() {
	*x = BreakerStatusResponse{}
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreakerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakerStatusResponse) ProtoMessage() {}

func (x *BreakerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakerStatusResponse.ProtoReflect.Descriptor instead.
func (*BreakerStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_v1_limiter_proto_rawDescGZIP(), []int{5}
}

func (x *BreakerStatusResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *BreakerStatusResponse) GetState() BreakerState {
	if x != nil {
		return x.State
	}
	return BreakerState_BREAKER_STATE_UNSPECIFIED
}

func (x *BreakerStatusResponse) GetFailureCount() int64 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *BreakerStatusResponse) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BreakerStatusResponse) GetLastStateChangeUnixMs() int64 {
	if x != nil {
		return x.LastStateChangeUnixMs
	}
	return 0
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_v1_limiter_proto_rawDescGZIP(), []int{6}
}

func (x *ResetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ResetRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LimiterReset  bool                   `protobuf:"varint,1,opt,name=limiter_reset,json=limiterReset,proto3" json:"limiter_reset,omitempty"`
	BreakerReset  bool                   `protobuf:"varint,2,opt,name=breaker_reset,json=breakerReset,proto3" json:"breaker_reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_v1_limiter_proto_rawDescGZIP(), []int{7}
}

func (x *ResetResponse) GetLimiterReset() bool {
	if x != nil {
		return x.LimiterReset
	}
	return false
}

func (x *ResetResponse) GetBreakerReset() bool {
	if x != nil {
		return x.BreakerReset
	}
	return false
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_v1_limiter_proto_rawDescGZIP(), []int{8}
}

type MetricsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests         int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	AllowedRequests       int64                  `protobuf:"varint,2,opt,name=allowed_requests,json=allowedRequests,proto3" json:"allowed_requests,omitempty"`
	DeniedRequests        int64                  `protobuf:"varint,3,opt,name=denied_requests,json=deniedRequests,proto3" json:"denied_requests,omitempty"`
	ActiveLimiters        int64                  `protobuf:"varint,4,opt,name=active_limiters,json=activeLimiters,proto3" json:"active_limiters,omitempty"`
	ActiveCircuitBreakers int64                  `protobuf:"varint,5,opt,name=active_circuit_breakers,json=activeCircuitBreakers,proto3" json:"active_circuit_breakers,omitempty"`
	BreakerTrips          int64                  `protobuf:"varint,6,opt,name=breaker_trips,json=breakerTrips,proto3" json:"breaker_trips,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_v1_limiter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_v1_limiter_proto_rawDescGZIP(), []int{9}
}

func (x *MetricsResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *MetricsResponse) GetAllowedRequests() int64 {
	if x != nil {
		return x.AllowedRequests
	}
	return 0
}

func (x *MetricsResponse) GetDeniedRequests() int64 {
	if x != nil {
		return x.DeniedRequests
	}
	return 0
}

func (x *MetricsResponse) GetActiveLimiters() int64 {
	if x != nil {
		return x.ActiveLimiters
	}
	return 0
}

func (x *MetricsResponse) GetActiveCircuitBreakers() int64 {
	if x != nil {
		return x.ActiveCircuitBreakers
	}
	return 0
}

func (x *MetricsResponse) GetBreakerTrips() int64 {
	if x != nil {
		return x.BreakerTrips
	}
	return 0
}

var File_proto_limiter_v1_limiter_proto protoreflect.FileDescriptor

const file_proto_limiter_v1_limiter_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/limiter/v1/limiter.proto\x12\n" +
	"limiter.v1\"\xd9\x01\n" +
	"\fCheckRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\talgorithm\x18\x02 \x01(\x0e2\x15.limiter.v1.AlgorithmR\talgorithm\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x03R\bcapacity\x12\x12\n" +
	"\x04rate\x18\x04 \x01(\x01R\x04rate\x12\x1b\n" +
	"\twindow_ms\x18\x05 \x01(\x03R\bwindowMs\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x03R\x04cost\x12!\n" +
	"\fservice_name\x18\a \x01(\tR\vserviceName\"\xc4\x01\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x01R\tremaining\x12$\n" +
	"\x0eretry_after_ms\x18\x04 \x01(\x03R\fretryAfterMs\x12=\n" +
	"\rbreaker_state\x18\x05 \x01(\x0e2\x18.limiter.v1.BreakerStateR\fbreakerState\"\x80\x02\n" +
	"\x13RecordResultRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12D\n" +
	"\x1econsecutive_failures_threshold\x18\x03 \x01(\x03R\x1cconsecutiveFailuresThreshold\x12.\n" +
	"\x13recovery_timeout_ms\x18\x04 \x01(\x03R\x11recoveryTimeoutMs\x126\n" +
	"\x17probe_success_threshold\x18\x05 \x01(\x03R\x15probeSuccessThreshold\"\x83\x02\n" +
	"\x14RecordResultResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12?\n" +
	"\x0eprevious_state\x18\x02 \x01(\x0e2\x18.limiter.v1.BreakerStateR\rpreviousState\x12=\n" +
	"\rcurrent_state\x18\x03 \x01(\x0e2\x18.limiter.v1.BreakerStateR\fcurrentState\x12#\n" +
	"\rfailure_count\x18\x04 \x01(\x03R\ffailureCount\x12#\n" +
	"\rsuccess_count\x18\x05 \x01(\x03R\fsuccessCount\"9\n" +
	"\x14BreakerStatusRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xee\x01\n" +
	"\x15BreakerStatusResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12.\n" +
	"\x05state\x18\x02 \x01(\x0e2\x18.limiter.v1.BreakerStateR\x05state\x12#\n" +
	"\rfailure_count\x18\x03 \x01(\x03R\ffailureCount\x12#\n" +
	"\rsuccess_count\x18\x04 \x01(\x03R\fsuccessCount\x128\n" +
	"\x19last_state_change_unix_ms\x18\x05 \x01(\x03R\x15lastStateChangeUnixMs\"C\n" +
	"\fResetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\"Y\n" +
	"\rResetResponse\x12#\n" +
	"\rlimiter_reset\x18\x01 \x01(\bR\flimiterReset\x12#\n" +
	"\rbreaker_reset\x18\x02 \x01(\bR\fbreakerReset\"\x10\n" +
	"\x0eMetricsRequest\"\x92\x02\n" +
	"\x0fMetricsResponse\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12)\n" +
	"\x10allowed_requests\x18\x02 \x01(\x03R\x0fallowedRequests\x12'\n" +
	"\x0fdenied_requests\x18\x03 \x01(\x03R\x0edeniedRequests\x12'\n" +
	"\x0factive_limiters\x18\x04 \x01(\x03R\x0eactiveLimiters\x126\n" +
	"\x17active_circuit_breakers\x18\x05 \x01(\x03R\x15activeCircuitBreakers\x12#\n" +
	"\rbreaker_trips\x18\x06 \x01(\x03R\fbreakerTrips*|\n" +
	"\tAlgorithm\x12\x19\n" +
	"\x15ALGORITHM_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ALGORITHM_TOKEN_BUCKET\x10\x01\x12\x1c\n" +
	"\x18ALGORITHM_SLIDING_WINDOW\x10\x02\x12\x1a\n" +
	"\x16ALGORITHM_LEAKY_BUCKET\x10\x03*|\n" +
	"\fBreakerState\x12\x1d\n" +
	"\x19BREAKER_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14BREAKER_STATE_CLOSED\x10\x01\x12\x16\n" +
	"\x12BREAKER_STATE_OPEN\x10\x02\x12\x1b\n" +
	"\x17BREAKER_STATE_HALF_OPEN\x10\x032\x83\x03\n" +
	"\x12RateLimiterService\x12<\n" +
	"\x05Check\x12\x18.limiter.v1.CheckRequest\x1a\x19.limiter.v1.CheckResponse\x12Q\n" +
	"\fRecordResult\x12\x1f.limiter.v1.RecordResultRequest\x1a .limiter.v1.RecordResultResponse\x12W\n" +
	"\x10GetBreakerStatus\x12 .limiter.v1.BreakerStatusRequest\x1a!.limiter.v1.BreakerStatusResponse\x12<\n" +
	"\x05Reset\x12\x18.limiter.v1.ResetRequest\x1a\x19.limiter.v1.ResetResponse\x12E\n" +
	"\n" +
	"GetMetrics\x12\x1a.limiter.v1.MetricsRequest\x1a\x1b.limiter.v1.MetricsResponseBCZAgithub.com/jimmyrom1/rate-limiter-grpc/proto/limiter/v1;limiterv1b\x06proto3"

var (
	file_proto_limiter_v1_limiter_proto_rawDescOnce sync.Once
	file_proto_limiter_v1_limiter_proto_rawDescData []byte
)

func file_proto_limiter_v1_limiter_proto_rawDescGZIP() []byte {
	file_proto_limiter_v1_limiter_proto_rawDescOnce.Do(func() {
		file_proto_limiter_v1_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_limiter_v1_limiter_proto_rawDesc), len(file_proto_limiter_v1_limiter_proto_rawDesc)))
	})
	return file_proto_limiter_v1_limiter_proto_rawDescData
}

var file_proto_limiter_v1_limiter_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_limiter_v1_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_limiter_v1_limiter_proto_goTypes = []any{
	(Algorithm)(0),                // 0: limiter.v1.Algorithm
	(BreakerState)(0),             // 1: limiter.v1.BreakerState
	(*CheckRequest)(nil),          // 2: limiter.v1.CheckRequest
	(*CheckResponse)(nil),         // 3: limiter.v1.CheckResponse
	(*RecordResultRequest)(nil),   // 4: limiter.v1.RecordResultRequest
	(*RecordResultResponse)(nil),  // 5: limiter.v1.RecordResultResponse
	(*BreakerStatusRequest)(nil),  // 6: limiter.v1.BreakerStatusRequest
	(*BreakerStatusResponse)(nil), // 7: limiter.v1.BreakerStatusResponse
	(*ResetRequest)(nil),          // 8: limiter.v1.ResetRequest
	(*ResetResponse)(nil),         // 9: limiter.v1.ResetResponse
	(*MetricsRequest)(nil),        // 10: limiter.v1.MetricsRequest
	(*MetricsResponse)(nil),       // 11: limiter.v1.MetricsResponse
}
var file_proto_limiter_v1_limiter_proto_depIdxs = []int32{
	0,  // 0: limiter.v1.CheckRequest.algorithm:type_name -> limiter.v1.Algorithm
	1,  // 1: limiter.v1.CheckResponse.breaker_state:type_name -> limiter.v1.BreakerState
	1,  // 2: limiter.v1.RecordResultResponse.previous_state:type_name -> limiter.v1.BreakerState
	1,  // 3: limiter.v1.RecordResultResponse.current_state:type_name -> limiter.v1.BreakerState
	1,  // 4: limiter.v1.BreakerStatusResponse.state:type_name -> limiter.v1.BreakerState
	2,  // 5: limiter.v1.RateLimiterService.Check:input_type -> limiter.v1.CheckRequest
	4,  // 6: limiter.v1.RateLimiterService.RecordResult:input_type -> limiter.v1.RecordResultRequest
	6,  // 7: limiter.v1.RateLimiterService.GetBreakerStatus:input_type -> limiter.v1.BreakerStatusRequest
	8,  // 8: limiter.v1.RateLimiterService.Reset:input_type -> limiter.v1.ResetRequest
	10, // 9: limiter.v1.RateLimiterService.GetMetrics:input_type -> limiter.v1.MetricsRequest
	3,  // 10: limiter.v1.RateLimiterService.Check:output_type -> limiter.v1.CheckResponse
	5,  // 11: limiter.v1.RateLimiterService.RecordResult:output_type -> limiter.v1.RecordResultResponse
	7,  // 12: limiter.v1.RateLimiterService.GetBreakerStatus:output_type -> limiter.v1.BreakerStatusResponse
	9,  // 13: limiter.v1.RateLimiterService.Reset:output_type -> limiter.v1.ResetResponse
	11, // 14: limiter.v1.RateLimiterService.GetMetrics:output_type -> limiter.v1.MetricsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_limiter_v1_limiter_proto_init() }
func file_proto_limiter_v1_limiter_proto_init() {
	if File_proto_limiter_v1_limiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_limiter_v1_limiter_proto_rawDesc), len(file_proto_limiter_v1_limiter_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_limiter_v1_limiter_proto_goTypes,
		DependencyIndexes: file_proto_limiter_v1_limiter_proto_depIdxs,
		EnumInfos:         file_proto_limiter_v1_limiter_proto_enumTypes,
		MessageInfos:      file_proto_limiter_v1_limiter_proto_msgTypes,
	}.Build()
	File_proto_limiter_v1_limiter_proto = out.File
	file_proto_limiter_v1_limiter_proto_goTypes = nil
	file_proto_limiter_v1_limiter_proto_depIdxs = nil
}
